version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: src/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
